export const reverseString = (str: string) => str.split("").reverse().join("");

export const numWordToStr: { [key: number | string]: string } = {
  one: "1",
  eno: "1",
  1: "1",
  two: "2",
  owt: "2",
  2: "2",
  three: "3",
  eerht: "3",
  3: "3",
  four: "4",
  ruof: "4",
  4: "4",
  five: "5",
  evif: "5",
  5: "5",
  six: "6",
  xis: "6",
  6: "6",
  seven: "7",
  neves: "7",
  7: "7",
  eight: "8",
  thgie: "8",
  8: "8",
  nine: "9",
  enin: "9",
  9: "9",
};
